FROM python:3.8.5-buster

# Install related packages
RUN pip install \
    tqdm \
    numpy \ 
    pytz pandas python-dateutil \
    scipy threadpoolctl joblib scikit-learn

# Install pytorch
# typing-extensions, torch, pillow, torchvision, torchaudio
RUN pip3 install \
    torch==1.8.1+cpu torchvision==0.9.1+cpu torchaudio===0.8.1 \
    -f https://download.pytorch.org/whl/torch_stable.html

# COPY data directory
COPY ./data/simplecaptcha /home/data

WORKDIR /home/Captcha
VOLUME /home/Captcha

ENTRYPOINT ["/bin/bash"]

